import Head from "next/head";
import { useRouter } from "next/router";
import {useState,useEffect } from 'react';

export default function Bolt() {
  const baseApiURL = "http://localhost:8000/api/v1/boltok/";
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const router = useRouter();
  const { id } = router.query;

  const fetchData = () => {
    fetch(`${baseApiURL}${id}`, {
      method: "DELETE",
      headers: {
        "Content-type": "application/json",
      },
    })
      .then((res) => {
        if (res.ok) {
          console.log("HTTP request successful");
        } else {
          console.log("HTTP request unsuccessful");
        }
        return res;
      })
      .then((res) => res.json())
      .then((data) => {
        setData(data);
      })
      .catch((error) => console.log(error));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{id}</p>
      </main>
    </div>
  );
}
