import Head from "next/head";
import { useRouter } from "next/router";
import {useState,useEffect } from 'react';
import { Card,Spin } from 'antd';

export default function Bolt() {
  const baseApiURL = "http://localhost:8000/api/v1/boltok/";
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const router = useRouter();
  const { id } = router.query;

  const fetchData = () => {
    setLoading(true);

    fetch(`${baseApiURL}${id}`)
      .then((res) => {
        if (res.ok) {
          console.log("HTTP request successful");
        } else {
          console.log("HTTP request unsuccessful");
        }
        return res;
      })
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);

      })
      .catch((error) => console.log(error));
  };

  useEffect(() => {
    fetchData();
  }, [router.isReady]);

  if (!data){
    return (
      <div style={{marginTop:"50px",height:"100%",display:"flex",justifyContent:"center",alignItems:"center"}}>
        <Spin />
      </div>
    )
  } 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div>
        <Card
          title={data.nev}
          bordered={true}
        >
          <p>Partner: {data.partner.nev}</p>
          <p>Penztargepeg száma: {data.penztargepek.length}</p> 
          
         
        </Card>
      </div>
      </main>
    </div>
  );
}
