version: "3.2"
services:
  backend:
    restart: always
    container_name: backend
    command : bash -c "python manage.py migrate &&
                      python manage.py shell -c ""from django.contrib.auth.models import User; User.objects.create_superuser("admin", "admin@example.com", "adminpass")"" &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - net

  frontend:
    restart: always
    command : yarn dev
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - net

networks:
  net:
    driver: bridge