# Generated by Django 4.0.5 on 2022-06-22 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cikk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=256)),
                ('cikkszam', models.CharField(max_length=256)),
                ('vonalkod', models.CharField(max_length=256)),
                ('mennyisegiegyseg', models.CharField(max_length=256)),
                ('nettoegysegar', models.FloatField()),
                ('verzio', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Penztargep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bolt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penztargepek', to='shop.bolt')),
            ],
        ),
        migrations.CreateModel(
            name='Vasarlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esemenydatumido', models.DateTimeField(default=django.utils.timezone.now)),
                ('vasarlasosszeg', models.FloatField()),
                ('bolt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasarlasok', to='shop.bolt')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasarlasok', to='shop.partner')),
                ('penztargep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasarlasok', to='shop.penztargep')),
            ],
        ),
        migrations.CreateModel(
            name='VasarlasTetel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.FloatField()),
                ('brutto', models.FloatField()),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasarlas_tetelek', to='shop.partner')),
                ('partnercikk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasarlas_tetelek', to='shop.cikk')),
                ('vasarlas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vasarlas_tetelek', to='shop.vasarlas')),
            ],
        ),
        migrations.AddField(
            model_name='cikk',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikkek', to='shop.partner'),
        ),
        migrations.AddField(
            model_name='bolt',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boltok', to='shop.partner'),
        ),
    ]
